# Generated by Django 3.0.5 on 2022-04-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Storage', models.IntegerField()),
                ('Stat', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
